version: '3.8'
name: crm
services:
  crm-frontend-svc:
    build: .
    container_name: crm-frontend
    image: crm-frontend-image
    ports:
      - "3002:3000"  # Aapka frontend jis port pe chalta ho
    env_file:
      - .env
    restart: always